CREATE DATABASE SUCOS_VENDAS_01

CREATE DATABASE SUCOS_VENDAS_02
ON (NAME=SUCOS_VENDAS_DAT, FILENAME='C:\Temp\TREINANDO_SQL.MDF', SIZE=10, MAXSIZE=50, FILEGROWTH=5)
LOG ON (NAME=SUCOS_VENDAS_LOG, FILENAME='C:\Temp\TREINANDO_SQL.LDF', SIZE=10, MAXSIZE=50, FILEGROWTH=5)