
CREATE TABLE [TABELA DE ALIMENTOS](
[NÚMERO DO ALIMENTO] [SMALLINT]NOT NULL,
[DESCRIÇÃO DOS ALIMENTOS] [VARCHAR] (50),
[ENERGIA] [FLOAT],
[PROTEÍNA] [FLOAT],
[CARBOIDRATO] [FLOAT] ,
[LIPIDIOS] [FLOAT] )