ALTER TABLE[TABELA DE ALIMENTOS]
ALTER COLUMN [ENERGIA]FLOAT NOT NULL

ALTER TABLE [TABELA DE ALIMENTOS]
ALTER COLUMN [CARBOIDRATO] FLOAT  NOT NULL

ALTER TABLE [TABELA DE ALIMENTOS]
ALTER COLUMN[PROTEÍNA] FLOAT  NOT NULL

ALTER TABLE [TABELA DE ALIMENTOS]
ALTER COLUMN [LIPIDIOS] FLOAT  NOT NULL